### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by joshmar** [m-wrzr/populartimes#107]
Heey heey, 

I noticed an error with the SSL while trying to use the code.
In the Crawler.py at line 369 the ssl.SSLContext(ssl.PROTOCOL_TLSv1) is called however this doesnt seem to work anymore.

what does seem to work is the following:
ssl.create_default_context()

Hope it helps!

Thank you so much for the awesome code you made!

**Comment by spykard** [comment]
https://github.com/m-wrzr/populartimes/pull/106
