### ISSUE TITLE
Regarding current_popularity field

### ISSUE THREAD

**Issue by rlangelo** [m-wrzr/populartimes#14]
Hello, first of all, thanks for the API. When I use populartimes.get_current("API-Key", "Place_ID"), one of the fields returned is current_popularity. I was wondering if there is any guide to what the returned numbers actually mean. I did a call "populartimes.get_current("MY_API_KEY", "ChIJQV94FwYZqwcR3p4mqAgqg-8") and it returned 25 for the field current_popularity. First of all, this is live data, correct? Second, how is it possible to translate this number to know how busy it actually is or not in the establishment? Thanks so much for the help and I apologize if this was a "stupid" question.

**Comment by m-wrzr** [comment]
Hey,
yeah, the current popularity shows the live data for a place. This is an estimation by Google based on anonymous android data they collect. Check out https://www.quora.com/How-does-the-Google-Maps-Popular-Times-feature-work for a more detailed answer.

The popularity represents the relative amount of people Google thinks are visiting the establishment. It's not completely clear how this is calculated, but you can assume, that google keeps a record of when the place is most frequented, e.g. Friday 22:00 for some bar. All other popularities are then put in reference to this point in time and the popularities calculated.

This is only an estimate and does not inform you how many people are there in absolute term. (Not everybody uses Android/Google Maps or has location on) If two bars are both full on Friday evening, they would both show 100% popularity, even if one has room for 30 people and the other for 100.

Hope that answered your question.
