### ISSUE TITLE
Problem with the basic example : populartimes.get(...)

### ISSUE THREAD

**Issue by LokiSenju** [m-wrzr/populartimes#16]
Hello,
The example provided doesn't work. I have to stop the execution of the function
This error appears : 
`urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:645)>`
I install pyOpenSSL, but i still have the issue.

**Comment by tea-mo903** [comment]
I have the same problem, when calling .get(...) method

**Comment by m-wrzr** [comment]
Hey,
could you provide more information on your system/ssl etc. I'm not able to reproduce the error, the example works fine for me.

**Comment by LokiSenju** [comment]
Hello,
It's really weird, i don't encounter this problem with my other laptop. They use the same OS (Ubuntu 16.04). I'll try to find where is my problem, i close this thread.
