### ISSUE TITLE
Module 'populartimes' has no attribute

### ISSUE THREAD

**Issue by Moyaga** [m-wrzr/populartimes#18]
I'm tryin the example and I keep geting the same error, no matter if I use **`populartimes.get`**, **`populartimes.get_id`** or **`populartimes.get_current`**.

Always getting the same error:

**`AttributeError: module 'populartimes' has no attribute 'get_id'`**

Someone could help with this?

**Comment by m-wrzr** [comment]
Do you have a project file called `populartimes.py` in your project? That could lead to the confusion.

**Comment by Moyaga** [comment]
My fault it was that! Thanks
