### ISSUE TITLE
Possibility to get current popular time

### ISSUE THREAD

**Issue by Johnix1337** [m-wrzr/populartimes#2]
I'm using your library for getting the average popular times, but is it possible to get the current popular time of the place?

![current](https://user-images.githubusercontent.com/1659532/29337819-18a894d6-8213-11e7-9c45-658d14750b0f.PNG)

I tried to reverse engineer the response of google but didn't find a way to retrieve the current popular time.

**Comment by m-wrzr** [comment]
Hey,

the URL where we get the data from and its JSON response has no current popular times data available.
Looking at the network traffic, there is a www.google.de/maps/preview/entity request, which contains the current popularity. However, it seems to require a protocol buffer parameter.

It could be possible to retrieve the current popular times this way. We will look into that.

**Comment by irux** [comment]
I am really interested in this feature too. It would be great if you give some advice to get the data and implement it.

**Comment by zachary-m** [comment]
Any updates?

**Comment by m-wrzr** [comment]
Check out https://github.com/m-wrzr/populartimes/tree/current_popularity.
It should work so far, but I would like to test it more before it get's merged into master.

**Comment by zachary-m** [comment]
https://github.com/NikolaiT/GoogleScraper

**Comment by zachary-m** [comment]
Install the wheel via: pip3 install populartimes-2.0-py3.whl

This is not working for me. I am running Ubuntu's latest LTS. 
I get this error: 

Requirement 'populartimes-2.0-py3.whl' looks like a filename, but the file does not exist
populartimes-2.0-py3.whl is not a valid wheel filename.

**Comment by zachary-m** [comment]
How could I use this with a placeID? I already have a location and I want the info on the specific location?

**Comment by m-wrzr** [comment]
To find a specific place/google id you can use the scraper or this: https://developers.google.com/maps/documentation/javascript/examples/places-placeid-finder.

Did you switch to the correct branch and removed the previously installed package? It works find for me.

**Comment by zachary-m** [comment]
Is there any way to use python to scrape the location ID given the address?

**Comment by m-wrzr** [comment]
You should be able to use https://developers.google.com/places/web-service/search?hl=en#TextSearchRequests if you want to use a specific address

**Comment by deeznuts03** [comment]
would it be possible to:

1) make get_current() have geofence parameters just like get(), to output current popularity for all places inside the fence?

2) add the logic for get_current() to the innards of get(), so that get() will return all data it already does plus "current_popularity: xx"?

Those would make certain processes much faster!

**Comment by deeznuts03** [comment]
And can you please share how to export this data into a readable format? I just get it all as one giant string. CSV and/or excel export would be ideal, but even a better format in python IDLE is good for now.

**Comment by m-wrzr** [comment]
Hey @deeznuts03 
The current popularity is now available via the normal populartimes.get(). #6 

I don't think it is necessary to add geofence parameters to get_current(), as there are now already two ways how to retrieve the data for an area.  Either with get() or if you wan't faster requests just save the place-ids in this location and call get_current().

The library is supposed to be a lightweight and easy option for people to retrieve the data and then work with it. By keeping to the python types and returning the data as a dict, this is guaranteed most IMO.

**Comment by m-wrzr** [comment]
Current popularity is now available #6

**Comment by deeznuts03** [comment]
Hey @m-wrzr thanks a ton! Looks like there are some awesome updates! I'm pretty new to python, so I'm a bit slow on understanding how all of this works and how to leverage your updates. I think you have helped me greatly though, and I am very thankful for the efforts.

**Comment by jkldgoefgkljefogeg** [comment]
What is the unit/range of popularity? Is the number comparable between building of different sizes (stadium with 50 people vs restaurant with 50 people, the restaurant is likely to be far more crowded)?
