### ISSUE TITLE
Does populartimes.get() still work?

### ISSUE THREAD

**Issue by SidTheEngineer** [m-wrzr/populartimes#21]
Following the example for `populartimes.get()`, the only thing I've gotten this to do is infinite loop in the console with coordinates until it surpasses the Google Places API quota.

**Comment by m-wrzr** [comment]
Could you provide params for your `.get()`?

**Comment by SidTheEngineer** [comment]
I was testing it out like this:

```Python
import populartimes

if __name__ == '__main__':
    results = populartimes.get('my_api_key', ['bar'], (37.4221145, -122.0860002), (37.4228775, -122.085133), radius=5)
    print(results)
```

**Comment by m-wrzr** [comment]
Hey, sorry for the late reply.
This is a bug, also discussed in #4 it will get fixed tomorrow.
