### ISSUE TITLE
Visit duration and Wait time estimates

### ISSUE THREAD

**Issue by rmateus** [m-wrzr/populartimes#24]
Would it be possible to extend the output from this amazing library to include also:
- Visit duration
- Wait time estimates

https://support.google.com/business/answer/6263531?hl=en

**Comment by m-wrzr** [comment]
hey @rmateus 
sorry for the late reply. Could you provide some places that show this information?

I wasn't able to find any examples where visit duration and wait time estimates are displayed.

**Comment by m-wrzr** [comment]
Seems like the information described above is only available on mobile apps so far. In case it is added to the web interface I'll try to include it.

**Comment by iffa** [comment]
Visit duration is shown for me on the web interface for pretty much any place I search for.
![firefox_2018-03-14_09-08-57](https://user-images.githubusercontent.com/759522/37388103-c6d68794-2767-11e8-821b-9aa581a5e6f2.png)

**Comment by m-wrzr** [comment]
It does not show at any place for me. Maybe its just rolling out on the web?

**Comment by iffa** [comment]
Probably rolling out yes, just now checked on another device and I see both visit duration and wait estimates :D
