### ISSUE TITLE
Live information changed

### ISSUE THREAD

**Issue by irux** [m-wrzr/populartimes#25]
Hello.

I think google has changed the position of the live information. I am trying to search the information in the endpoint that the module creates and makes a request but I think they don't response with the correct Live info anymore.

the past week, it seems like google was making changes to this system because it didn't work for some days.

Maybe the Protobuf is not valid anymore for the live information.

Someone an idea?

Thank you

**Comment by m-wrzr** [comment]
Hey,

yeah it looks like the live information is not available currently, its not even displayed on google maps..

**Comment by m-wrzr** [comment]
Looks like the information is back up and everything works again as expected.

**Comment by irux** [comment]
yes ... you are right. Thank you!
