### ISSUE TITLE
Live place is not working (Again)

### ISSUE THREAD

**Issue by irux** [m-wrzr/populartimes#29]
Can someone test it ? or is it only me ?

**Comment by m-wrzr** [comment]
The data is currently not provided by google maps...

**Comment by irux** [comment]
Ok thank you. I ask because in the google search the data is available but in Google maps is not and I didn't know that the endpoint use the information in Google maps.

Thank you again

**Comment by SquareRooT1** [comment]
This data is available now. If you need it you can check it.
