### ISSUE TITLE
Multiple types does not work.

### ISSUE THREAD

**Issue by raffie-** [m-wrzr/populartimes#33]
If I key in multiple types, populartimes.get() will only return results of the first type. For example:
populartimes.get(api_key = API_KEY,
                            types = ['gym','bar'],
                            p1 = (l1, l2), 
                            p2 = (l3, l4),
                            all_places=False)
This will only return places of type "gym", whereas
populartimes.get(api_key = API_KEY,
                            types = ['bar','gym'],
                            p1 = (l1, l2), 
                            p2 = (l3, l4),
                            all_places=False)
This will only return places of type "bar". How do I use the codes to return all places as long as it has type of either "bar" or "gym"?

**Comment by raffie-** [comment]
https://developers.google.com/places/web-service/search#deprecation

Apparently according to the site above, the API will only take the first type and ignore the rest.

"
type — Restricts the results to places matching the specified type. Only one type may be specified (if more than one type is provided, all types following the first entry are ignored). See the list of supported types.
"

**Comment by m-wrzr** [comment]
Hey @raffie- 
thanks for the information. I thinks it is some legacy issue because the crawler was working different previously. I'll try to fix it soon!

**Comment by cna274** [comment]
Hi, I am working on this API. I was wondering the popular times (hourly) we get from populartimes.get() method, is it real time ?

**Comment by m-wrzr** [comment]
@cna274 no, but the current popularity is realtime when its available

**Comment by zorluh** [comment]
Dear all, I am looking for ways to get only one specific field after using get_id. for example, I dont need international phone number, Can I update the code to get particular fields?

thanks!

**Comment by m-wrzr** [comment]
@vanhaster you can provide a empty array for the type parameter to receive everything.

@zorluh you can get the fields you want the same way as from any python dictionary `res["current_popularity"]`
