### ISSUE TITLE
JSON parsing errors

### ISSUE THREAD

**Issue by eprochasson** [m-wrzr/populartimes#35]
Hi,

it appears Google sometimes return multiple response for a given `place_identifier`, in `get_populartimes` and `get_current_popularity`. Multiple entries are separated with `/*""*/`. It seems that only the first entry is relevant.

I encountered this problem with `place_identifier = "'Osteria Amici Miei 信義區仁愛路四段502號之一, 信義區台北市 Taiwan 110'"`, but I can't consistently reproduce this behavior.

A fix is to patch the `get_populartimes` and `get_current_popularity` function when decoding the response:

```data = resp.read().decode('utf-8').split('/*""*/')[0]```

I'm happy to make a pull request, I do not know the API well enough to know if this is a satisfactory fix though.

**Comment by m-wrzr** [comment]
Hey @eprochasson 
your fix should be sufficient, I added it in the latest commit.
Thanks!!
