### ISSUE TITLE
GUI with Request

### ISSUE THREAD

**Issue by wghun86** [m-wrzr/populartimes#38]
@m-wrzr , thank you for this. Populartimes is great for amateur business intelligence gathering. I'm using your tool as my base for learning Python. This is my first little bit of code for a GUI using the get.id function. I'm going to constantly update this and plan on doing the following: 
Creating a drop-down menu to choose different requests
Converting returned JSON to CSV
Not submitting when user has not entered information
Much more

For now, I'd love for you to try out my get.id "program"

`from tkinter import *
from tkinter import Entry

import populartimes

def submit():
    api_key = entry_1.get()
    place_id = entry_2.get()
    print(api_key)
    print(place_id)
    result = populartimes.get_id(api_key, place_id)
    print(result)

root = Tk()

label_1 = Label(text="API Key")
label_2 = Label(text="Place ID")
entry_1 = Entry()
entry_2 = Entry()

label_1.grid(row=0)
label_2.grid(row=1)

entry_1.grid(row=0, column=1)
entry_2.grid(row=1, column=1)

button_1 = Button(text="Submit", command=submit)
button_1.grid()

root.mainloop()
`

**Comment by deeznuts03** [comment]
Hey wghun86! I'm actually using the populartimes tool for similar learning
purposes, but I'm struggling a bit. If you're open to it, I'd love to play
around with your program or even look over the code for everything as you
progress to try to understand it and learn how to apply the concepts to my
future projects. Feel free to reach out to me directly if you want to
discuss further.

**Comment by m-wrzr** [comment]
@wghun86 much success developing and learning python! It's a great language.

**Comment by m-wrzr** [comment]
I'll close this for now as it is not really a problem with the library or a feature request. But feel free to continue updating this issue!
