### ISSUE TITLE
What is pb variable?

### ISSUE THREAD

**Issue by pravdomil** [m-wrzr/populartimes#40]
Do anybody know what `pb` variable is?

https://github.com/m-wrzr/populartimes/blob/a5205d7fc909ca09dd18ad5de2dcbd0096cfc817/populartimes/crawler.py#L254

**Comment by m-wrzr** [comment]
It's a custom format used by google maps. [This](http://blog.themillhousegroup.com/2016/08/deep-diving-into-google-pb-embedded-map.html)  blog post gives a nice overview of the _pb_ parameter for embedded maps.

The _pb_ string used in the code is just a static version, which has to be provided/parsed by maps, but the data is specified via the _q_ parameter.

**Comment by pravdomil** [comment]
Some more information:

 *  http://stackoverflow.com/a/34275131/1852838
 *  http://stackoverflow.com/a/24662610/1852838
