### ISSUE TITLE
Radar search is deprecated

### ISSUE THREAD

**Issue by riedmaph** [m-wrzr/populartimes#41]
Radar search will be turned down on June 30, 2018. We should switch to the new Nearby Search or Text Search. The request looks quite similar, so it should be easy to change. It also returns more information about the places, so we probably can get rid of the additional detail search.
However, it will return far less results: 20 per request instead of 200 with radar search. Up to 60 places  for a given location & radius can be obtained with repeated calls using a pagetoken (20 per page).
This means we have to reduce the search radius to obtain all results.

**Comment by Porter97** [comment]
The pricing structure should be changing rather considerably as well, from 150000 a day for free with a billing account set up to around 5000 per month. This kind of crimps the availability of nearby search as an option (you would have to cycle through all the available categories of business and aggregate with async requests, burning through your free quota rather quickly).

**Comment by riedmaph** [comment]
This is unfortunate, but at least we don't need the detail search anymore (used to be one request per place), so the nearby requests are the only thing that counts towards your quota. Assuming one request returns 10 places on average you can at least process 50,000 places per month.
The best we can do is improving our covering algorithm (``get_circle_centers``) to minimize the number of requests required to cover the search area.
