### ISSUE TITLE
Huge amount of requests being sent to Google?

### ISSUE THREAD

**Issue by stefankruijt** [m-wrzr/populartimes#42]
When I'm trying to do a request for a small area there are thousands of requests being made to Google. For instance:

lat1 = 36.150182
long1 = -86.783909
lat2 = 36.152166
long2 = -86.779082

data = populartimes.get(apiKey,["bar"], (lat1, long1), (lat2, long2))
print(data)

I would expect a few calls since there should be at most 20 bars in that area. But in just a few minutes of trying I already hit the error: "You exceeded your Query Limit for Google Places API Web Service"

When I checked the Google console I had a 1000 requests. I upgraded my Google Account to the free limit of 150.000 
But it looks like the request above makes at least 1000 requests? What am I doing wrong? Within minutes I suddenly already made 65,000 requests.
I do see correct data coming back, so it's working great. But I would like to just make the right amount of calls to Google to not create a huge bill.

**Comment by m-wrzr** [comment]
Hey, 
this is definitely vastly above the normal amount of requests. I ran the example above locally and only generated about 10 requests.

Could you provide more information on the type of queries that were sent to google (radar or detail)?

**Comment by Porter97** [comment]
The issue here revolves around the way that this library finds data. There is essentially two requests happening 1) there is a "Radar Search" via the google places API, and this finds the businesses in any given area.  This is also the one that consumes the API call resources. The second part takes the businesses returned by the google API call, aggregates them and sends out requests to the google search API (in this case via a maps search). The returned result is then parsed and the results are provided in a formatted JSON. That explained, the reason why you are incurring so many requests relative to the returned results is the fact that the API charges by returned results **regardless of whether those requests have populartimes data** as such, and especially covering rural areas, there are a  number of businesses that are not large enough to have this data, but still count against the API call limit.

My suggestion is either a) Search incrementally over time, saving results to a database or b) create a fork of  this library that takes in the "place_identifiers" of each business (preferably ones that  you have found give populartimes data) and search those individually at will, sidestepping the API calls altogether.

**Comment by stefankruijt** [comment]
@Porter97 I don't really understand why my request would generate so many requests. I choose gps coordinates of just a really small part of the city here. When I look at the map there are probably only 13 bars/restaurants in that area. 
So I would expect only a number of requests that equals the numbers of businesses in a given area?

Could it be that Google also has a minimum amount of time between requests?
I'm doing this on a 2017 Macbook Pro and I see that Google says in their rules:

**You can exceed the Google Maps APIs web services usage limits by:

Sending too many requests per day.
Sending requests too fast, i.e. too many requests per second.**

Could it be that my requests are being sent too fast?
Not sure though how I could have created 65,000 requests... But in the beginning, when I just started I might have had my gps swapped.

**Comment by Porter97** [comment]
That is bizarre, two quick questions:

What (if any) is the surrounding code? is there a loop function, concurrency, etc?

Also, how long did it take for your script to run?

**Comment by stefankruijt** [comment]
I don't have any concurrency or loops in my code. (See below)
It only takes a few seconds for my script to run. I see about about 24 times the following below. So I guess there are about 24 businesses in this area and every call fails with the "OVER_QUERY_LIMIT".
I'll already double checked my query limit, but I'm still way below 150,000. So I'm not over my query limit.

Exception in thread Thread-6:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/populartimes/crawler.py", line 104, in worker_radar
    get_radar(item[0], item[1])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/populartimes/crawler.py", line 112, in get_radar
    check_response_code(resp)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/populartimes/crawler.py", line 387, in check_response_code
    "You exceeded your Query Limit for Google Places API Web Service, "
populartimes.crawler.PopulartimesException: ('Google Places OVER_QUERY_LIMIT', 'You exceeded your Query Limit for Google Places API Web Service, check https://developers.google.com/places/web-service/usage to upgrade your quota.')


Code:

`import populartimes

apiKey = "API_KEY"

def hello_world():

    lat1 = 36.140126
    long1 = -86.787082

    lat2 = 36.153166
    long2 = -86.779909

    data = populartimes.get(apiKey,["restaurant"], (lat1, long1), (lat2, long2))
    print(data)
    for location in data:
        if('current_popularity' in location):
            print("Location name: " + location['name'] + " is has current popularity of: " + str(location['current_popularity']))

hello_world()`

**Comment by stefankruijt** [comment]
Yes that must have been it I guess. After I upgraded the quota to 150,000 I didn't create a new API key. Right now it's working fine :)

One more small question about the number of requests. Does the radar search already filter on type of business (like restaurants)? Or are calls made for every single business within the search area and then filtered?
I would like to request data from the entire city with for instance "restaurants", but if there is a request made for every single business I've to be really careful with the number of times I can do this before I hit the limit of 150,000.

**Comment by Porter97** [comment]
From what I can see it does/should filter by type, limiting t he number of API requests. Be careful with typing mistakes though, capitalization anywhere (as in "Bar", instead of "bar") results in a general (as in no filter search).
