### ISSUE TITLE
help for installing please

### ISSUE THREAD

**Issue by chriskonnerth** [m-wrzr/populartimes#43]
hi, Im really bad at this so Im stuck. I think i have everything set up. What do you mean with "run pip install" or "import populartimes" ? 
My goal is to use the populartimes data for my Chatbot.

**Comment by m-wrzr** [comment]
Please check [this](https://docs.python.org/3/tutorial/index.html) and [this](https://docs.python.org/3/tutorial/venv.html#managing-packages-with-pip) to find out more about how python as well as pip works.
