### ISSUE TITLE
Syntaxerror for unexpected word

### ISSUE THREAD

**Issue by cryptomix** [m-wrzr/populartimes#49]
Hey, 

I cloned and installed it, however when I run the populartimes.get_id() it stops at the api key and gives out a syntaxerror for unexpected word. 

How can I fix this? Is this common?

**Comment by m-wrzr** [comment]
Can you post the error message?

**Comment by cryptomix** [comment]
`bash: Syntaxfehler beim unerwarteten Wort `"AIzaSyAZ1vK2Z9tV5Ck86sWndNYgpGPXLiavqW",'
`

**Comment by m-wrzr** [comment]
You should not post your API key here. It looks like you didn't run it in the python console.

**Comment by cryptomix** [comment]
fixed by actually opening the python console.

t. n00b
