### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by deeznuts03** [m-wrzr/populartimes#5]
Hello - I am extremely new to Python and crawler execution, so I am unsure of how to run this code. Would it be possible for you to record a brief video tutorial on:

1) How to install the required software (if any) required to run your code
2) How to properly place all of the code in a directory that can be accessed for running the code
3) How to install the wheel file
4) Where/how to run the the final file

I'm hoping this request isn't too difficult or time consuming!

Thank you!

**Comment by deeznuts03** [comment]
Would you be able to further explain the number of threads, radius, and Boolean usage as well? I don't understand how to properly use those function inputs. 

Thanks again!

**Comment by alex-waters** [comment]
I've tried pip installing this package but both pip and conda say they can't find it?

**Comment by deeznuts03** [comment]
Yeah I had to re-install python and check the box for "add pip to PATH". 

I do wonder if there is an easy way to download the data to a CSV, and I would like to also add phone number information to the data. Those would both be very useful to me.

**Comment by m-wrzr** [comment]
There are currently no plans to make a video tutorial, however I updated the readme and hope everything is clearer now.

@alex-waters The repo is currently not available online, so cloning and installing locally is the way to go.

@deeznuts03 the number of threads allows multitasking and leads to a faster execution. the radius is for the radarsearch, check out https://developers.google.com/places/web-service/search#RadarSearchRequests and the all_places bool can be used if you want to retrieve all places in the location, not just the ones with available populartimes data.
