### ISSUE TITLE
Deprecation warning: Vincencty is deprecated

### ISSUE THREAD

**Issue by mfkaptan** [m-wrzr/populartimes#57]
It seems geopy deprecated Vincencty and they propose using something else:

```
DeprecationWarning: Vincenty is deprecated and is going to be removed in geopy 2.0. 
Use `geopy.distance.geodesic` (or the default `geopy.distance.distance`) instead, 
which is more accurate and always converges.
```

**Comment by m-ad** [comment]
By now, this has happened. In geopy 2.x support for vincenty distance was dropped, see https://geopy.readthedocs.io/en/stable/changelog_2xx.html#breaking-changes:

> Removed geopy.distance.vincenty, use geopy.distance.geodesic instead.

**Comment by m-wrzr** [comment]
#97
