### ISSUE TITLE
Google Billing Update

### ISSUE THREAD

**Issue by sarmstr5** [m-wrzr/populartimes#64]
FYI - Google Billing seems to have changed since the aboutme was written.  For instance the about me says: "(for more than 1000 requests/sec add payment information)".  I think you have to have payment information regardless.  

My question is: I am trying to figure out the costs per query and I am not sure what the sku is for the query.  Are these geocode requests?  If so, looks like you get 40k requests a month with current monthly [credit.](https://cloud.google.com/maps-platform/pricing/sheet/#places) 

R/
Shane

**Comment by Porter97** [comment]
Sadly these requests are billed under the highest places information requests (Places + Basic Data + Contact Data + Atmosphere Data), which given current rates allows for 5000 requests under the 200$ credit

**Comment by sarmstr5** [comment]
Thanks Porter!  I really appreciate it!  I would recommend putting that in the AboutMe.md.

**Comment by sarmstr5** [comment]
I submitted a PR to update the README.md with the information provided above by Porter97.
