### ISSUE TITLE
publishing/citing populartimes

### ISSUE THREAD

**Issue by gabriel-happle** [m-wrzr/populartimes#67]
Hi @m-wrzr,
Thank you very much for providing this code open-source!
I'm using your code to gather data for a scientific publication.
How should your code be cited/acknowledged?
You can find me here if you have any concerns or questions: http://www.fcl.ethz.ch/people/Researchers/GabrielHapple.html

This is our main project by the way:
https://github.com/architecture-building-systems/CityEnergyAnalyst

**Comment by m-wrzr** [comment]
hey @gabriel-happle 

looks really cool what you guys are building with the CEA! For citing you can check https://github.com/m-wrzr/populartimes/issues/39#issuecomment-388784341 

Would be nice if you post here again once your work is published, always interesting to see what people do with the data.
