### ISSUE TITLE
how to create plugins file from setup.py

### ISSUE THREAD

**Issue by DGP13** [m-wrzr/populartimes#68]
I need this json type of data into my iOS application. please provide me steps of installations

**Comment by m-wrzr** [comment]
hey @DGP13 ,

please check https://github.com/m-wrzr/populartimes#how-to-get-started for installation instructions. Depending on your usecase you'll have to setup your own backend to integrate it into iOS.

**Comment by DGP13** [comment]
i need plugin for ios
