### ISSUE TITLE
How to change crawler.py

### ISSUE THREAD

**Issue by deeznuts03** [m-wrzr/populartimes#7]
Hello - I am trying to change some stuff on my own in crawler.py, but when I do the changes are not reflected in my results. Is there something I need to do to make those edits fill into my running code. Basically, I'm trying to make current popularity unavailable = -1 as it was in the prior version, but when I turn this code: 

    try:
        # get info from result array, has to be adapted if backend api changes
        info = jdata[0][1][0][14]
        return info[84][7][1]

    # ignore, there is either no info available or no popular times
    # TypeError: rating/rating_n/populartimes in None
    # IndexError: info is not available
    except (TypeError, IndexError):
        return None

into this code:

    try:
        # get info from result array, has to be adapted if backend api changes
        info = jdata[0][1][0][14]
        return info[84][7][1]

    # ignore, there is either no info available or no popular times
    # TypeError: rating/rating_n/populartimes in None
    # IndexError: info is not available
    except (TypeError, IndexError):
        return -1

it still returns none and has no "current_popularity" in the json object.

**Comment by deeznuts03** [comment]
I have figured out how to do a check for "current_popularity" in the json object and impute -1 if unavailable via these lines in my code:

    if 'current_popularity' in currentPopData:
        currentPop = currentPopData['current_popularity']
    else:
        currentPop = -1

But I would still love to know how to make and implement changes in the overall crawler, so I can make any future edits that I want (and have the skills to implement) on my own. Any help from anybody is much appreciated!

**Comment by m-wrzr** [comment]
Hey @deeznuts03 

I guess your problem is this:
If you apply changes in crawler.py, the pip installed package does not change. The pip wheel has to be build again, uninstalled and installed.

You can build a new wheel with:
`python3 setup.py bdist_wheel`
or just import the module locally and not install via pip.

Did this solve your problem?

**Comment by deeznuts03** [comment]
Would I use that line of code in the terminal/cmd (mac/pc)?

And how do I import it locally and not install via pip? 

Hopefully I'm not asking too many stupid questions here, I'm just trying to learn how this works! You are very helpful :)

**Comment by m-wrzr** [comment]
Yes, you have to run this code in the terminal. I'm not sure why the bdist_wheel error happens, maybe you ran it in the wrong folder, or some file was missing?

For information on imports check https://docs.python.org/3/reference/import.html. Basically you just have to add the populartimes code as a python module/package to your current project.
