### ISSUE TITLE
How to interpret popular times data

### ISSUE THREAD

**Issue by kkhangv** [m-wrzr/populartimes#71]
My three quick questions, can anyone of you please help me out? 
1. The date is from 1-7, I wonder if 1 means Monday and 7 means Sunday?
2. The poptime index is from 0-100 with 0 being close - is it relative or absolute? Aka 20 minutes wait at a restaurant may be long but a 20 wait at the ER is nothing. 
3. Google has a "minute" estimate, is there a way to translate the index to minute? Or better yet, is there a way to scrape it by the hour and day of the week?

**Comment by m-wrzr** [comment]
Hey,

1. The normal response already has a weekday returned, were 0=Monday and 6=Sunday, so not sure what you mean there?
2. The `populartimes` field shows how many people are in the place relative to the most busy time of the week (100% can still mean there is some space left, but it's as busy as it gets at this place). 
3. This would be the `time_wait` field
