### ISSUE TITLE
Documentation for search points

### ISSUE THREAD

**Issue by JosiahParry** [m-wrzr/populartimes#72]
I'm currently using the api and I'm placing two points  `p1 = (42.3567157,-71.0649089); p2 = (42.3524027,-71.0676424)`. This returns 0 results but I am seeing that the this is hitting the API in the google console. 

Could you provide documentation as to how the search area is created? i.e. is the first point the top left area of a square and the p2 the bottom right?

**Comment by sedlund** [comment]
https://github.com/m-wrzr/populartimes/blob/master/populartimes/crawler.py#L114

>     :param b1: south-west bounds [lat, lng]
>     :param b2: north-east bounds [lat, lng]

**Comment by JosiahParry** [comment]
Thank you for showing me that. That documentation isn't shown in the jupyter lab docstring.

<img width="807" alt="Screen Shot 2019-04-20 at 16 44 36" src="https://user-images.githubusercontent.com/13534508/56462121-a6b51500-638b-11e9-9161-0c89f0efd301.png">
