### ISSUE TITLE
Places without Popular Times

### ISSUE THREAD

**Issue by runneals** [m-wrzr/populartimes#75]
This doesn't appear to work with locations that do not have popular times listed when accessed via google maps. Is that correct?

**Comment by vermaat** [comment]
In the crawler.py file i can see the following line:

> if params["all_places"] or "populartimes" in detail_json:
>         results.append(detail_json)

I am not sure what 'all_places' mean, but it seems to only add the place to the final results if either the populartimes is included or 'all_places' is in the results.

**Comment by lbedogni** [comment]
all_places simply means that you want the result regardless of populartimes. If you set it to false, it will not add the detailed information in case populartimes is not available.
