### ISSUE TITLE
Populartimes available for location but unable

### ISSUE THREAD

**Issue by andreian02** [m-wrzr/populartimes#76]
![image](https://user-images.githubusercontent.com/36339564/58743767-930ccc00-846a-11e9-8488-79b6c527280a.png)

![image](https://user-images.githubusercontent.com/36339564/58743779-b899d580-846a-11e9-9c61-c4f5ce5a4c13.png)

Not sure why there was no populartimes available.

**Comment by vermaat** [comment]
I'm having similar issues with a lot of places. I'm getting a respone with the correct place_id and address but the popular time data is missing.

**Comment by vermaat** [comment]
I did some further research. I checked the 'Upper Changi MRT station' on Google maps through my browser. I noticed that the Popular Time was not available. When I use my VPN through Singapore the Popular time data IS available. 
After that I played a bit with proxies and VPN's for the popular times request. I was able to get popular time data for this station in Singapore, but not consistent....

To be updated

**Comment by lfvd** [comment]
Same issue here. In my case, I've collected hundreds of Place ID's, all of which had Popular Times data in Google Maps, but many of them didn't return this data when using the command. All of them are at the same country, so as my connection. Is there any explanation or procedure to get this data through the command?

Now the other way around: if popular times is not available on Google Maps, does it mean that it may be available through the command?

**Comment by m-wrzr** [comment]
Hey @lfvd 

can you send me some of the place IDs where the data was available via Google Maps but not the library?
If the data isn't available on Google Maps you also can't get it via the command.

**Comment by andreian02** [comment]
Hello Vermaat, 

No VPN on my end, I am able to retrieve the populartimes on 'Upper Changi MRT station', just tested it. 

Hello m-wrzr, 
Could i share one place ids where data is available on google maps but cant retrieve using library? 

Do try these 2 for an example, "ChIJ3R4LA4oQ2jERNSHfbiszO48" , "ChIJPYxKUwQZ2jER7KUuPbBTsUQ"
which is beauty world mrt station singapore and bayfront mrt station singapore. 

Thank you!

**Comment by m-wrzr** [comment]
Hey @andreian02 

so it seems like both examples don't have a proper address on Google Maps (only Singapore, no streets etc.) which is used to construct the `/search` request using a formatted address. Maps uses a different endpoint insead for this edgecase: `/maps/preview/place?....&q=beauty world singapore` - at least according to the network requests.

I'll try to add this as a fallback option for cases like the one you described. Thanks for your quick reply! Sry for my late one!

**Comment by m-wrzr** [comment]
#100

**Comment by lfvd** [comment]
Hello, @m-wrzr 
I was on summer holidays so couldn't reply promptly =)

Attached I send a spreadsheet where all the places which have popular times data on Maps weren't retrievable by the tool. If you could take a look and give some help, I'd appreciate.

[Places not found.xlsx](https://github.com/m-wrzr/populartimes/files/5110048/Places.not.found.xlsx)

If you'd like any further info, just ask. Thanks a lot!

Luiz

**Comment by andreian02** [comment]
Hello @m-wrzr , 

Sorry, could I ask what you mean is that because those locations do not have a proper address listed on Google Maps hence even though there is data available, we are unable to query the results? 

Thank you!
