### ISSUE TITLE
Help with running  this project on mac

### ISSUE THREAD

**Issue by SharedMocha** [m-wrzr/populartimes#77]
Hi,
I am trying to run this project on mac. I git cloned and did pip install .  and it all looks good.
Now, how do I run methods/function so I can pass API key and places id?
I am new to Python. Any help is appreciated.  When i run the commandd 'populartimes.get_id("my_key_here_", "ChIJSYuuSx9awokRyrrOFTGg0GY")' it gives '-bash: syntax error near unexpected token `"my_key_here",''

**Comment by m-wrzr** [comment]
hey, hope you got into python more, it's a great language. seems like you didn't run the program from the python cli
