### ISSUE TITLE
Not displaying current popularity?

### ISSUE THREAD

**Issue by smallzZz8** [m-wrzr/populartimes#79]
Hello, 

So basically the title describes it all. I am having trouble getting the current popularity to display. Has google removed this?

I have tried printing out the array that is returning None for current popularity but I can not find a way to figure out what is what in that document.

Any suggestions?

**Comment by m-wrzr** [comment]
Can you provide the place ID for debugging?

**Comment by smallzZz8** [comment]
> Can you provide the place ID for debugging?

ChIJ6boeiFVo54gRQtAjnHHuu7o

**Comment by h3artofeverything** [comment]
![image](https://user-images.githubusercontent.com/36339564/70976935-cef63e80-20e7-11ea-9b74-cc3e5123ec8a.png)

Dont see the current popularity. 
Documentation says this: 

The information present for places is highly varying. Therefore popularity, current_popularity, rating, rating_n, time_wait, time_spent and phone are optional return parameters and only present if available.

Perhaps its no longer available.

**Comment by guidopowell** [comment]
Hi, does current popularity work for other locations?
I am also hoping to get a historical log of current popularity. Is there any chance that is available somewhere?
Thank you

**Comment by m-wrzr** [comment]
Hey, you'd have to store the historical log yourself. The library can only retrieve the current snapshot from the Google Maps website.
