### ISSUE TITLE
What does popular times measure exactly?

### ISSUE THREAD

**Issue by zhiwenchong** [m-wrzr/populartimes#86]
From [Google](https://support.google.com/business/answer/6263531?hl=en):

> Shows how busy your location typically is during different times of the day. Popular times are based on average popularity over the last several weeks. Popularity for any given hour is shown relative to the typical peak popularity for the business for the week. For example, in the image below, 6:00PM-7:00PM on Thursday is one of the more popular times of the week for this business. 

When I call the API, it returns a number between 0-100% for every hour of each day of the week. This a long shot I wonder if anyone here knows (or can deduce):

* The "average popularity over the last several weeks" -- how many past weeks? 
* How often is this baseline updated and when does it occur (daily? weekly?)

Just wondering if anyone had any insights.

**Comment by akanelson** [comment]
Same question here.
How do I get the number of people that % represent so I can compare two different places?

**Comment by Bellador** [comment]
you would need some actual customer number statistics to calibrate your model to these relative numbers provided by Google to be able to obtain total numbers and compare them between places. One must always consider that this data anyway only considers a portion of the Android User base - so already an approximation in itself

**Comment by m-wrzr** [comment]
see #91

**Comment by julian59189** [comment]
@Bellador are you sure about the android portion? Maybe everyone using Google Maps?

**Comment by Bellador** [comment]
@julian59189 I wouldn't deny that Google Maps users are taken into consideration but I would argue that it is a smaller share. Let me explain. It is know that during Google Street View runs also the Wireless Networks of a City besides the road network image data is mapped in detail. Android devices have been shown to actively and passively send the wireless networks and their respective signal strengths to Google which would allow for a positioning/triangulation if the locations of these routers are known. And given the previous described mapping by Google most of which are. They are often associated with a specific (bigger) establishment/shop, which are also the ones that show popular times data on Google Maps if you pay attention - which is only a fraction of all shops out there. These shops normally have some sort of 'free' wifi with their shop name in the wireless name. Unfortunately I cannot give you concrete citations to underline my statement, therefore take it as my personal opinion.

**Comment by julian59189** [comment]
I agree with you 100%.
I think first of all there is a portion of people having iphone using apple maps. No way to get their data.
And yeah I think on IOS apps cannot scan for wifi networks (unless you have a special permission handed out by apple, which I couldn't image apple want to give to google).
I was thinking those populartimes are solely made up out of gps data but it makes so much more sense to use wifi triangulation because gps won't work well indoors.
