### ISSUE TITLE
why module 'populartimes' has no attribute 'get_id'?

### ISSUE THREAD

**Issue by luacy200820** [m-wrzr/populartimes#93]
I have downloaded populartimes, and import populartimes is successful.
But I failed using populartimes.get_id (..., ...).
Is the installation failed?

**Comment by Stanley-Zheng** [comment]
I have the same issue, how did you solve it?

**Comment by Stanley-Zheng** [comment]
For future users, don't name your file populartimes.py. I am very dumb, and got an error since it was referencing itself.
