### ISSUE TITLE
ModuleNotFoundError: No module named 'urllib3'

### ISSUE THREAD

**Issue by JuanEL0** [m-wrzr/populartimes#94]
Hi!

I am working in a Flask project and I tried to integrate this package into it but when I added it (following the instructions) at the moment that I ran my server, it crashed with a `ModuleNotFoundError: No module named 'urllib3'` even when I had it installed.

After some hours making different stuff to fix it I realized that I had `urllib3==1.24.3` then I tried upgrading it and it fixed the problem.

Now my current urllib3 is the version 1.25.9 and it works as it should. I am new on Python (that was the reason I spent hours trying to figure out this problem) but I think that adding some restrictions to `setuptools` should fix this problem.

Thanks

**Comment by m-wrzr** [comment]
Hey,

so i couldn't replicate your issue with urllib3 `1.24.3` specifically, it works fine with flask and in general as far as i tested. There might have been some other issues with the installation.
I found some warnings with versions `<=1.20` though and added that as a minimal requirement.

In case you can replicate the issue with `urllib3==1.24.3` let me know and I'll reopen this.
